def response_data(report_id):
    data = [
        {
            'id': 1,
            'order_id': 'DETEL100001094',
            'customer_details': 'Vijay Kumar',
            'mobile': '8287088830',
            'email': 'Vijaykumar62702@gmail.com',
            'item_name': 'Detel D1 Champ',
            'item_qty': '1',
            'item_sku': 'D1 Champ',
            'total_amount': '575',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '575',
            'bank_amount': '575',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 2,
            'order_id': 'DETEL100001097',
            'customer_details': 'Awadhesh Kumar',
            'mobile': '9161910966',
            'email': 'awdkm@ymail.com',
            'item_name': 'DetelPro Thermometer DT09 Plus @ 1099 Plus GST',
            'item_qty': '1',
            'item_sku': 'Detelpro DT09+',
            'total_amount': '1297',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '1297',
            'bank_amount': '1297',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 3,
            'order_id': 'DETEL100001109',
            'customer_details': 'BEST FINANCE CORPORATION LIMITED',
            'mobile': '8344494004',
            'email': 'rmadmin@bestfinance.in',
            'item_name': 'DetelPro Thermometer DT09 Plus @ 1099 Plus GST',
            'item_qty': '1',
            'item_sku': 'Detelpro DT09+',
            'total_amount': '1297',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '1297',
            'bank_amount': '1297',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 4,
            'order_id': 'DETEL100001111',
            'customer_details': 'Swarup patait',
            'mobile': '9767405915',
            'email': 'patait.swarupsinh55@gmail.com',
            'item_name': 'DetelPro Thermometer DT09 @ 999 Plus GST',
            'item_qty': '1',
            'item_sku': 'DetelPro DT09',
            'total_amount': '1179',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '1179',
            'bank_amount': '1179',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 5,
            'order_id': 'DETEL100001126',
            'customer_details': 'Pradeep suhag',
            'mobile': '9992919148',
            'email': 'pradeepsuhag.cityinnovates@gmail.com',
            'item_name': 'Detel D1 Champ',
            'item_qty': '1',
            'item_sku': 'D1 Champ',
            'total_amount': '575',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '575',
            'bank_amount': '575',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 6,
            'order_id': 'DETEL100001130',
            'customer_details': 'shripathy s.p.',
            'mobile': '9944776949',
            'email': 'pradeepsuhag.cityinnovates@gmail.com',
            'item_name': 'Detel D1 Champ',
            'item_qty': '1',
            'item_sku': 'D1 Champ',
            'total_amount': '575',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '575',
            'bank_amount': '575',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 7,
            'order_id': 'DETEL100001144',
            'customer_details': 'mahendra vyavhare',
            'mobile': '9619480848',
            'email': 'mahendra7222@gmail.cim',
            'item_name': 'DetelPro Thermometer DT09 @ 999 Plus GST',
            'item_qty': '1',
            'item_sku': 'DetelPro DT09',
            'total_amount': '1179',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '1179',
            'bank_amount': '1179',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 8,
            'order_id': 'DETEL100001138',
            'customer_details': 'SHIVENDRA VERMA',
            'mobile': '9888668757',
            'email': 'shivendram.verma@gmail.com',
            'item_name': 'Amaze Festive Dhamaka Offer',
            'item_qty': '1',
            'item_sku': 'Amaze',
            'total_amount': '943',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '943',
            'bank_amount': '943',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 9,
            'order_id': 'DETEL100001152',
            'customer_details': 'VENKATESWARA RAO S',
            'mobile': '8754079777',
            'email': 'rao@4ccs.in',
            'item_name': 'Detel Collar @ 499 Plus GST',
            'item_qty': '1',
            'item_sku': 'Collar',
            'total_amount': '589',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '589',
            'bank_amount': '589',
            'open_amount': '0.0',
            'outstanding': '0.0'
        },
        {
            'id': 10,
            'order_id': 'DETEL100001169',
            'customer_details': 'Nanda gopala',
            'mobile': '9663881234',
            'email': 'nandagopala8287@gmail.com',
            'item_name': 'DetelPro Thermometer DT09 Plus @ 1099 Plus GST',
            'item_qty': '1',
            'item_sku': 'Detelpro DT09+',
            'total_amount': '1297',
            'txn_id': 'pay_FW8nXkdM47GYAu',
            'settlement_id': 'setl_FXHzjXudsY9uwt',
            'settlement_amount': '1297',
            'bank_amount': '1297',
            'open_amount': '0.0',
            'outstanding': '0.0'
        }
    ]
    return data
