# Generated by Django 2.2 on 2021-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_auto_20210215_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
