# Generated by Django 2.2 on 2021-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0004_uploadfiles_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
