# Generated by Django 2.2 on 2021-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0006_totalreconcile'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalreconcile',
            name='bank_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalreconcile',
            name='open_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalreconcile',
            name='reconcile_t1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalreconcile',
            name='reconcile_t2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalreconcile',
            name='reconcile_t3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalreconcile',
            name='settlement_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
