# Generated by Django 2.2 on 2021-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0008_auto_20210429_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalreconcile',
            name='bank_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='open_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='settlement_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
