# Generated by Django 2.2 on 2021-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0009_auto_20210429_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_t1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_t2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_t3',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
