# Generated by Django 2.2 on 2021-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0010_auto_20210430_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalreconcile',
            name='ageing_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='bank_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='open_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_t1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_t2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='reconcile_t3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='sales_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalreconcile',
            name='settlement_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
