# Generated by Django 2.2 on 2021-04-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usercompanylogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompanylogo',
            old_name='company_logo',
            new_name='logo',
        ),
    ]
