# Generated by Django 2.2 on 2021-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210428_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanylogo',
            name='logo',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
